# Generated by Django 3.2.9 on 2022-01-18 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tata_rec',
            fields=[
                ('Ticket_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Date_of_Issue', models.DateField(blank=True, null=True)),
                ('Time_of_Issue', models.TimeField(blank=True, null=True)),
                ('Form', models.CharField(blank=True, max_length=500, null=True)),
                ('Method', models.CharField(blank=True, max_length=500, null=True)),
                ('Issue', models.CharField(blank=True, max_length=500, null=True)),
                ('Caller_ID_Number', models.CharField(blank=True, max_length=500, null=True)),
                ('Type_of_Call_or_Messge', models.CharField(blank=True, max_length=500, null=True)),
                ('Advertiser_Business_Number', models.CharField(blank=True, max_length=500, null=True)),
                ('City', models.CharField(blank=True, max_length=500, null=True)),
                ('State', models.CharField(blank=True, max_length=500, null=True)),
                ('Zip', models.IntegerField()),
                ('Location_Center_point_of_the_Zip_Code', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
