# Generated by Django 3.2.9 on 2022-01-18 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tata_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tata_rec',
            name='Advertiser_Business_Number',
            field=models.CharField(blank=True, default=None, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='tata_rec',
            name='Caller_ID_Number',
            field=models.CharField(blank=True, default=None, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='tata_rec',
            name='City',
            field=models.CharField(blank=True, default=None, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='tata_rec',
            name='Date_of_Issue',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='tata_rec',
            name='Form',
            field=models.CharField(blank=True, default=None, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='tata_rec',
            name='Issue',
            field=models.CharField(blank=True, default=None, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='tata_rec',
            name='Location_Center_point_of_the_Zip_Code',
            field=models.CharField(blank=True, default=None, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='tata_rec',
            name='Method',
            field=models.CharField(blank=True, default=None, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='tata_rec',
            name='State',
            field=models.CharField(blank=True, default=None, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='tata_rec',
            name='Time_of_Issue',
            field=models.TimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='tata_rec',
            name='Type_of_Call_or_Messge',
            field=models.CharField(blank=True, default=None, max_length=500, null=True),
        ),
    ]
